spring.application.name=expence-tracker

spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker
spring.datasource.username=root
spring.datasource.password=Somu@6458


# spring.sql.init.mode=always//any db is connected it will read
spring.sql.init.mode=never
# never will never read the data
# spring.sql.init.mode=embeded used when h2 database is used ,

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# create =>first drop then recreate

# ,create-drop => first create at startup then drop at shutdown

# ,update,: 
# validate: used in production : 
# ,none: used in production , no cmmd will work
# ,create only,drop,truncate